### ISSUE TITLE
i don't know this is project issue or my pc issue plz help

### ISSUE THREAD

**Issue by prabhatghimire** [Samrid-Pandit/nepse-api#34]
i got this error after i import Client from nepse

>>> import asyncio
>>> import httpx
>>> from nepse import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/nepse/__init__.py", line 1, in <module>
    from .core import Client
  File "/usr/local/lib/python3.9/dist-packages/nepse/core.py", line 5, in <module>
    from nepse.broker.core import BrokerClient
  File "/usr/local/lib/python3.9/dist-packages/nepse/broker/__init__.py", line 1, in <module>
    from .core import BrokerClient
  File "/usr/local/lib/python3.9/dist-packages/nepse/broker/core.py", line 9, in <module>
    from nepse.utils import _ClientWrapperHTTPX
  File "/usr/local/lib/python3.9/dist-packages/nepse/utils.py", line 40, in <module>
    @attr.frozen
AttributeError: module 'attr' has no attribute 'frozen'

**Comment by prabhatghimire** [comment]
and i try https://newweb.nepalstock.com/api/ api from react directly its shows cross origin error how can i use this api directly in react without any issue?

thanks in advance

**Comment by CaffeineDuck** [comment]
If its a library issue, I will try to fix it by releasing a patch as fast as possible but for now, you can do:
```py
pip uninstall attr
pip install attrs
```
Thank you for reporting this issue

**Comment by CaffeineDuck** [comment]
@prabhatghimire Tell me if it works or not

**Comment by CaffeineDuck** [comment]
I just released new version of `nepse-api` you can update it using pip as well, and it will also fix the issue. Please update me wheather the issue still persists or is fixed.

**Comment by CaffeineDuck** [comment]
Closing this issue as the author hasn't replied.

**Comment by prabhatghimire** [comment]
it worked :+1:  after installing attrs package
